class QuranApi {
  static const List surahLocal = <dynamic>[
    {
      "id": 1,
      "name": "Al-Faatihah",
      "aya": 7,
      "malay": "Pembuka",
      "english": "The Opening",
      "place": "Makkah",
      "arabic": "الفَاتِحَة",
    },
    {
      "id": 2,
      "name": "Al-Baqarah",
      "aya": 286,
      "malay": "Lembu betina",
      "english": "The Cow",
      "place": "Madinah",
      "arabic": "البَقَرَة",
    },
    {
      "id": 3,
      "name": "A-li’ Imraan",
      "aya": 200,
      "malay": "Keluarga Imran",
      "english": "The Family of Imran",
      "place": "Madinah",
      "arabic": "آل عِمْرَان",
    },
    {
      "id": 4,
      "name": "An-Nisaa’",
      "aya": 176,
      "malay": "Wanita",
      "english": "The Women",
      "place": "Madinah",
      "arabic": "النِّسَاء",
    },
    {
      "id": 5,
      "name": "Al-Maa’Idah",
      "aya": 120,
      "malay": "Hidangan",
      "english": "The Table",
      "place": "Madinah",
      "arabic": "المَائدة",
    },
    {
      "id": 6,
      "name": "Al-An’aam",
      "aya": 165,
      "malay": "Binatang Ternakan",
      "english": "The Cattle",
      "place": "Makkah",
      "arabic": "الأنعَام",
    },
    {
      "id": 7,
      "name": "Al-A’raaf",
      "aya": 206,
      "malay": "Tempat Tertinggi",
      "english": "The Heights",
      "place": "Makkah",
      "arabic": "الأعْرَاف",
    },
    {
      "id": 8,
      "name": "Al-Anfaal",
      "aya": 75,
      "malay": "Harta Rampasan Perang",
      "english": "The Spoils of War",
      "place": "Madinah",
      "arabic": "الأنْفَال",
    },
    {
      "id": 9,
      "name": "At-Taubah",
      "aya": 129,
      "malay": "Taubat",
      "english": "The Repentance",
      "place": "Madinah",
      "arabic": "التّوبَة",
    },
    {
      "id": 10,
      "name": "Yunus",
      "aya": 109,
      "malay": "Yunus",
      "english": "Jonas",
      "place": "Makkah",
      "arabic": "يُونسْ",
    },
    {
      "id": 11,
      "name": "Hud",
      "aya": 123,
      "malay": "Nabi Hud",
      "english": "Hud",
      "place": "Makkah",
      "arabic": "هُود",
    },
    {
      "id": 12,
      "name": "Yusuf",
      "aya": 111,
      "malay": "Nabi Yusuf",
      "english": "Joseph",
      "place": "Makkah",
      "arabic": "يُوسُف",
    },
    {
      "id": 13,
      "name": "Ar-Ra'd",
      "aya": 43,
      "malay": "Guruh",
      "english": "The Thunder",
      "place": "Madinah",
      "arabic": "الرّعْد",
    },
    {
      "id": 14,
      "name": "Ibrahim",
      "aya": 52,
      "malay": "Nabi Ibrahim",
      "english": "Abraham",
      "place": "Makkah",
      "arabic": "إبراهيْم",
    },
    {
      "id": 15,
      "name": "Al-Hijr",
      "aya": 99,
      "malay": "Penduduk Kota Hijr",
      "english": "The Rock",
      "place": "Makkah",
      "arabic": "الحِجْر",
    },
    {
      "id": 16,
      "name": "An-Nahl",
      "aya": 128,
      "malay": "Lebah",
      "english": "The Bee",
      "place": "Makkah",
      "arabic": "النّحْل",
    },
    {
      "id": 17,
      "name": "Al-Israa'",
      "aya": 111,
      "malay": "Perjalanan Nabi daripada Masjidil Haram ke Masjidil Aqsa",
      "english": "The Night Journey",
      "place": "Makkah",
      "arabic": "الإسْرَاء",
    },
    {
      "id": 18,
      "name": "Al-Kahfi",
      "aya": 110,
      "malay": "Gua",
      "english": "The Cave",
      "place": "Makkah",
      "arabic": "الكهْف",
    },
    {
      "id": 19,
      "name": "Maryam",
      "aya": 98,
      "malay": "Maryam",
      "english": "Mary",
      "place": "Makkah",
      "arabic": "مَريَمْ",
    },
    {
      "id": 20,
      "name": "Taha",
      "aya": 135,
      "malay": "Taha",
      "english": "Taa Haa",
      "place": "Makkah",
      "arabic": "طه",
    },
    {
      "id": 21,
      "name": "Al-Anbiyaa'",
      "aya": 112,
      "malay": "Nabi-Nabi",
      "english": "The Prophets",
      "place": "Makkah",
      "arabic": "الأنبيَاء",
    },
    {
      "id": 22,
      "name": "Al-Hajj",
      "aya": 78,
      "malay": "Ibadah Haji",
      "english": "The Pilgrimage",
      "place": "Madinah",
      "arabic": "الحَجّ",
    },
    {
      "id": 23,
      "name": "Al-Mukminun",
      "aya": 118,
      "malay": "Orang yang Beriman",
      "english": "The Believers",
      "place": "Makkah",
      "arabic": "المؤمنون",
    },
    {
      "id": 24,
      "name": "An-Nur",
      "aya": 64,
      "malay": "Cahaya",
      "english": "The Light",
      "place": "Madinah",
      "arabic": "النُّور",
    },
    {
      "id": 25,
      "name": "Al-Furqaan",
      "aya": 77,
      "malay": "Pembeza",
      "english": "The Criterion",
      "place": "Makkah",
      "arabic": "الفُرْقان",
    },
    {
      "id": 26,
      "name": "Asy-Syu’araa’",
      "aya": 227,
      "malay": "Para Penyair",
      "english": "The Poets",
      "place": "Makkah",
      "arabic": "الشُّعَرَاء",
    },
    {
      "id": 27,
      "name": "An-Naml",
      "aya": 93,
      "malay": "Semut",
      "english": "The Ant",
      "place": "Makkah",
      "arabic": "النَّمْل",
    },
    {
      "id": 28,
      "name": "Al-Qasas",
      "aya": 88,
      "malay": "Cerita-Cerita",
      "english": "The Stories",
      "place": "Makkah",
      "arabic": "القصص",
    },
    {
      "id": 29,
      "name": "Al-’Ankabut",
      "aya": 69,
      "malay": "Labah-Labah",
      "english": "The Spider",
      "place": "Makkah",
      "arabic": "العَنكبوت",
    },
    {
      "id": 30,
      "name": "Ar-Ruum",
      "aya": 60,
      "malay": "Bangsa Rum",
      "english": "The Romans",
      "place": "Makkah",
      "arabic": "الرُّوم",
    },
    {
      "id": 31,
      "name": "Luqman",
      "aya": 34,
      "malay": "Luqman",
      "english": "Luqman",
      "place": "Makkah",
      "arabic": "لقمَان",
    },
    {
      "id": 32,
      "name": "As-Sajdah",
      "aya": 30,
      "malay": "Sujud",
      "english": "The Prostration",
      "place": "Makkah",
      "arabic": "السَّجْدَة",
    },
    {
      "id": 33,
      "name": "Al-Ahzaab",
      "aya": 73,
      "malay": "Golongan yang Bersekutu",
      "english": "The Clans",
      "place": "Madinah",
      "arabic": "الأحزَاب",
    },
    {
      "id": 34,
      "name": "Saba'",
      "aya": 54,
      "malay": "Kaum Saba’",
      "english": "Sheba",
      "place": "Makkah",
      "arabic": "سَبَاء",
    },
    {
      "id": 35,
      "name": "Faatir",
      "aya": 45,
      "malay": "Pencipta",
      "english": "The Originator",
      "place": "Makkah",
      "arabic": "فاَطِر",
    },
    {
      "id": 36,
      "name": "Yaa siin",
      "aya": 83,
      "malay": "Yaasin",
      "english": "Yaseen",
      "place": "Makkah",
      "arabic": "يسْ",
    },
    {
      "id": 37,
      "name": "As-Saaffaat",
      "aya": 182,
      "malay": "Yang Bersaf-Saf",
      "english": "Those Wdrawn up in Ranks",
      "place": "Makkah",
      "arabic": "الصَّافَات",
    },
    {
      "id": 38,
      "name": "Shod",
      "aya": 88,
      "malay": "Sad",
      "english": "The letter Saad",
      "place": "Makkah",
      "arabic": "ص",
    },
    {
      "id": 39,
      "name": "Az-Zumar",
      "aya": 75,
      "malay": "Rombongan-Rombongan",
      "english": "The Groups",
      "place": "Makkah",
      "arabic": "الزمر",
    },
    {
      "id": 40,
      "name": "Ghafir",
      "aya": 85,
      "malay": "Yang Maha Pengampun",
      "english": "The Forgiver",
      "place": "Makkah",
      "arabic": "غافر",
    },
    {
      "id": 41,
      "name": "Fussilat",
      "aya": 54,
      "malay": "Yang dijelaskan",
      "english": "Explain in detail",
      "place": "Makkah",
      "arabic": "فُصِّلَت",
    },
    {
      "id": 42,
      "name": "Asy-Syura",
      "aya": 53,
      "malay": "Musyawarah",
      "english": "Consultation",
      "place": "Makkah",
      "arabic": "ٱلشُّورىٰ",
    },
    {
      "id": 43,
      "name": "Az-Zukhruf",
      "aya": 89,
      "malay": "Perhiasan ",
      "english": "Ornaments of gold",
      "place": "Makkah",
      "arabic": "ٱلْزُّخْرُف",
    },
    {
      "id": 44,
      "name": "Ad-Dukhaan",
      "aya": 59,
      "malay": "Asap",
      "english": "The Smoke",
      "place": "Makkah",
      "arabic": "ٱلدُّخَان",
    },
    {
      "id": 45,
      "name": "Al-Jaathiyah",
      "aya": 37,
      "malay": "Yang berlutut",
      "english": "Crouching",
      "place": "Makkah",
      "arabic": "ٱلْجَاثِيَة",
    },
    {
      "id": 46,
      "name": "Al-Ahqaaf",
      "aya": 35,
      "malay": "Bukit-Bukit Pasir",
      "english": "The Dunes",
      "place": "Makkah",
      "arabic": "ٱلْأَحْقَاف",
    },
    {
      "id": 47,
      "name": "Muhammad",
      "aya": 38,
      "malay": "Nabi Muhammad",
      "english": "Muhammad",
      "place": "Madinah",
      "arabic": "مُحَمَّد",
    },
    {
      "id": 48,
      "name": "Al-Fat-h",
      "aya": 29,
      "malay": "Kemenangan",
      "english": "The Victory",
      "place": "Madinah",
      "arabic": "الفتح",
    },
    {
      "id": 49,
      "name": "Al-Hujuraat",
      "aya": 18,
      "malay": "Kamar-Kamar",
      "english": "The Inner Apartments",
      "place": "Madinah",
      "arabic": "ٱلْحُجُرَات",
    },
    {
      "id": 50,
      "name": "Qaaf",
      "aya": 45,
      "malay": "Qaf",
      "english": "The letter Qaaf",
      "place": "Makkah",
      "arabic": "ق",
    },
    {
      "id": 51,
      "name": "Adz-Zaariyaat",
      "aya": 60,
      "malay": "Angin Yang Menerbangkan",
      "english": "The Winnowing Wind",
      "place": "Makkah",
      "arabic": "ٱلذَّارِيَات",
    },
    {
      "id": 52,
      "name": "At-Tuur",
      "aya": 49,
      "malay": "Gunung Tursina",
      "english": "The Mount",
      "place": "Makkah",
      "arabic": "ٱلطُّور",
    },
    {
      "id": 53,
      "name": "An-Najm",
      "aya": 62,
      "malay": "Bintang",
      "english": "The Star",
      "place": "Makkah",
      "arabic": "ٱلنَّجْم",
    },
    {
      "id": 54,
      "name": "Al-Qamar",
      "aya": 55,
      "malay": "Bulan",
      "english": "The Moon",
      "place": "Makkah",
      "arabic": "ٱلْقَمَر",
    },
    {
      "id": 55,
      "name": "Ar-Rahmaan",
      "aya": 78,
      "malay": "Maha Pemurah",
      "english": "The Beneficentl",
      "place": "Madinah",
      "arabic": "ٱلرَّحْمَٰن",
    },
    {
      "id": 56,
      "name": "Al-Waaqi'ah",
      "aya": 96,
      "malay": "Hari Kiamat",
      "english": "The Inevitable",
      "place": "Makkah",
      "arabic": "ٱلْوَاقِعَة",
    },
    {
      "id": 57,
      "name": "Al-Hadiid",
      "aya": 29,
      "malay": "Besi",
      "english": "The Iron",
      "place": "Madinah",
      "arabic": "ٱلْحَدِيد",
    },
    {
      "id": 58,
      "name": "Al-Mujaadalah",
      "aya": 22,
      "malay": "Wanita yang Bersoal Jawab",
      "english": "The Pleading Woman",
      "place": "Madinah",
      "arabic": "ٱلْمُجَادلَة",
    },
    {
      "id": 59,
      "name": "Al-Hasy-r",
      "aya": 24,
      "malay": "Pengusiran",
      "english": "The Exile",
      "place": "Madinah",
      "arabic": "ٱلْحَشْر",
    },
    {
      "id": 60,
      "name": "Al-Mumtahanah",
      "aya": 13,
      "malay": "Perempuan yang Diuji",
      "english": "She that is to be examined",
      "place": "Madinah",
      "arabic": "ٱلْمُمْتَحَنَة",
    },
    {
      "id": 61,
      "name": "As-Saff",
      "aya": 14,
      "malay": "Dalam Barisan",
      "english": "The Ranks",
      "place": "Madinah",
      "arabic": "ٱلصَّفّ",
    },
    {
      "id": 62,
      "name": "Al-Jumu'ah",
      "aya": 11,
      "malay": "Hari Jumaat",
      "english": "Friday",
      "place": "Madinah",
      "arabic": "ٱلْجُمُعَة",
    },
    {
      "id": 63,
      "name": "Al-Munaafiquun",
      "aya": 11,
      "malay": "Orang-Orang Munafik",
      "english": "The Hypocrites",
      "place": "Madinah",
      "arabic": "المنَافِقون",
    },
    {
      "id": 64,
      "name": "At-Taghaabun",
      "aya": 18,
      "malay": "Hari Diperlihatkan Segala Kesalahan",
      "english": "Mutual Disillusion",
      "place": "Madinah",
      "arabic": "التغَابُن",
    },
    {
      "id": 65,
      "name": "At-Talaaq",
      "aya": 12,
      "malay": "Talak",
      "english": "Divorce",
      "place": "Madinah",
      "arabic": "الطلَاق",
    },
    {
      "id": 66,
      "name": "At-Tahriim",
      "aya": 12,
      "malay": "Mengharamkan",
      "english": "The Prohibition",
      "place": "Madinah",
      "arabic": "التحْريم",
    },
    {
      "id": 67,
      "name": "Al-Mulk",
      "aya": 30,
      "malay": "Kerajaan",
      "english": "The Sovereignty",
      "place": "Makkah",
      "arabic": "المُلْك",
    },
    {
      "id": 68,
      "name": "Al-Qalam",
      "aya": 52,
      "malay": "Pena",
      "english": "The Pen",
      "place": "Makkah",
      "arabic": "القَلَم",
    },
    {
      "id": 69,
      "name": "Al-Haaqqah",
      "aya": 52,
      "malay": "Hari Kiamat",
      "english": "The Reality",
      "place": "Makkah",
      "arabic": "الحَاقَّة",
    },
    {
      "id": 70,
      "name": "Al-Ma'aarij",
      "aya": 44,
      "malay": "Tempat-Tempat Naik",
      "english": "The Ascending Stairways",
      "place": "Makkah",
      "arabic": "المعَارج",
    },
    {
      "id": 71,
      "name": "Nuh",
      "aya": 28,
      "malay": "Nuh",
      "english": "Noah",
      "place": "Makkah",
      "arabic": "نُوح",
    },
    {
      "id": 72,
      "name": "Al-Jinn",
      "aya": 28,
      "malay": "Jin",
      "english": "The Jinn",
      "place": "makkah",
      "arabic": "الجِن",
    },
    {
      "id": 73,
      "name": "Al-Muzzammil",
      "aya": 20,
      "malay": "Orang yang Berselimut",
      "english": "The Enshrouded One",
      "place": "Makkah",
      "arabic": "المُزَّمِّل",
    },
    {
      "id": 74,
      "name": "Al-Muddaththir",
      "aya": 56,
      "malay": "Orang yang Berselimut",
      "english": "The Cloaked One",
      "place": "Makkah",
      "arabic": "المُدَّثِّر",
    },
    {
      "id": 75,
      "name": "Al-Qiyaamah",
      "aya": 40,
      "malay": "Hari Qiamat",
      "english": "The Resurrection",
      "place": "Makkah",
      "arabic": "القِيَامَة",
    },
    {
      "id": 76,
      "name": "Al-Insaan",
      "aya": 31,
      "malay": "Manusia",
      "english": "Man",
      "place": "Madinah",
      "arabic": "الإنسَان",
    },
    {
      "id": 77,
      "name": "Al-Mursalaat",
      "aya": 50,
      "malay": "Para Malaikat yang Diutus",
      "english": "The Emissaries",
      "place": "Makkah",
      "arabic": "المُرسَلات",
    },
    {
      "id": 78,
      "name": "An-Naba",
      "aya": 40,
      "malay": "Berita Besar",
      "english": "The Annoucement",
      "place": "Makkah",
      "arabic": "النَّبَأ",
    },
    {
      "id": 79,
      "name": "An-Naazi'aat",
      "aya": 46,
      "malay": "Para Malaikat yang Mencabut",
      "english": "Those Who Drag Forth",
      "place": "Makkah",
      "arabic": "النّازعَات",
    },
    {
      "id": 80,
      "name": "'Abasa",
      "aya": 42,
      "malay": "Dia Bermasam Muka",
      "english": "He Frowned",
      "place": "Makkah",
      "arabic": "عَبَس",
    },
    {
      "id": 81,
      "name": "At-Takwiir",
      "aya": 29,
      "malay": "Menggulung",
      "english": "The Overthrowing",
      "place": "Makkah",
      "arabic": "التَّكوير",
    },
    {
      "id": 82,
      "name": "Al-Infitaar",
      "aya": 19,
      "malay": "Terbelah",
      "english": "The Cleaving",
      "place": "Makkah",
      "arabic": "الانفِطار",
    },
    {
      "id": 83,
      "name": "Al-Mutaffifiin",
      "aya": 36,
      "malay": "Orang yang Curang",
      "english": "Defrauding",
      "place": "Makkah",
      "arabic": "المطفِّفِين",
    },
    {
      "id": 84,
      "name": "Al-Insyiqaaq",
      "aya": 25,
      "malay": "Terbelah",
      "english": "The Splitting Open",
      "place": "Makkah",
      "arabic": "الانْشِقَاق",
    },
    {
      "id": 85,
      "name": "Al-Buruuj",
      "aya": 22,
      "malay": "Gugusan Bintang",
      "english": "The Constellations",
      "place": "Makkah",
      "arabic": "البرُوج",
    },
    {
      "id": 86,
      "name": "At-Taariq",
      "aya": 17,
      "malay": "Yang Datang Di Malam Hari",
      "english": "The Morning Star",
      "place": "Makkah",
      "arabic": "الطَّارِق",
    },
    {
      "id": 87,
      "name": "Al-A'laa",
      "aya": 19,
      "malay": "Yang Paling Tinggi",
      "english": "The Most High",
      "place": "Makkah",
      "arabic": "الأَعْلى",
    },
    {
      "id": 88,
      "name": "Al-Ghaasyiyah",
      "aya": 26,
      "malay": "Hari Pembalasan",
      "english": "The Overwhelming",
      "place": "Makkah",
      "arabic": "الغَاشِية",
    },
    {
      "id": 89,
      "name": "Al-Fajr",
      "aya": 30,
      "malay": "Fajar",
      "english": "The Dawn",
      "place": "Makkah",
      "arabic": "الفَجْر",
    },
    {
      "id": 90,
      "name": "Al-Balad",
      "aya": 20,
      "malay": "Negeri",
      "english": "The City",
      "place": "Makkah",
      "arabic": "البَلَد",
    },
    {
      "id": 91,
      "name": "As-Syams",
      "aya": 15,
      "malay": "Matahari",
      "english": "The Sun",
      "place": "Makkah",
      "arabic": "الشَّمْس",
    },
    {
      "id": 92,
      "name": "Al-Lail",
      "aya": 21,
      "malay": "Malam",
      "english": "The Night",
      "place": "Makkah",
      "arabic": "الليْل",
    },
    {
      "id": 93,
      "name": "adh-Dhuha",
      "aya": 11,
      "malay": "Waktu Dhuha",
      "english": "The Morning Hours",
      "place": "Makkah",
      "arabic": "الضُّحَى",
    },
    {
      "id": 94,
      "name": "Al-Insyiraah",
      "aya": 8,
      "malay": "Kelapangan",
      "english": "The Consolation",
      "place": "Makkah",
      "arabic": "الشَّرْح",
    },
    {
      "id": 95,
      "name": "At-Tiin",
      "aya": 8,
      "malay": "Buah Tin",
      "english": "The Fig",
      "place": "Makkah",
      "arabic": "التِّين",
    },
    {
      "id": 96,
      "name": "Al-'Alaq",
      "aya": 19,
      "malay": "Segumpal Darah",
      "english": "The Clot",
      "place": "Makkah",
      "arabic": "العَلَق",
    },
    {
      "id": 97,
      "name": "Al-Qadr",
      "aya": 5,
      "malay": "Kemuliaan",
      "english": "The Power, Fate",
      "place": "Makkah",
      "arabic": "القَدْر",
    },
    {
      "id": 98,
      "name": "Al-Bayyinah",
      "aya": 8,
      "malay": "Bukti Yang Nyata",
      "english": "The Evidence",
      "place": "Madinah",
      "arabic": "البَينَة",
    },
    {
      "id": 99,
      "name": "Az-Zalzalah",
      "aya": 8,
      "malay": "Kegoncangan",
      "english": "The Earthquake",
      "place": "Madinah",
      "arabic": "الزلزَلة",
    },
    {
      "id": 100,
      "name": "Al-'Aadiyat",
      "aya": 11,
      "malay": "Kuda Perang",
      "english": "The Chargers",
      "place": "Makkah",
      "arabic": "العَادِيات",
    },
    {
      "id": 101,
      "name": "Al-Qaari'ah",
      "aya": 11,
      "malay": "Hari Kiamat",
      "english": "The Calamity",
      "place": "Makkah",
      "arabic": "القَارِعة",
    },
    {
      "id": 102,
      "name": "At-Takaathur",
      "aya": 8,
      "malay": "Bermegah-Megah",
      "english": "Competition",
      "place": "Makkah",
      "arabic": "التَّكَاثر",
    },
    {
      "id": 103,
      "name": "Al-'Asr",
      "aya": 3,
      "malay": "Masa",
      "english": "The Declining Day, Epoch",
      "place": "Makkah",
      "arabic": "العصر",
    },
    {
      "id": 104,
      "name": "Al-Humazah",
      "aya": 9,
      "malay": "Pengumpat",
      "english": "The Traducer",
      "place": "Makkah",
      "arabic": "الهُمَزَة",
    },
    {
      "id": 105,
      "name": "Al-Fiil",
      "aya": 5,
      "malay": "Gajah",
      "english": "The Elephant",
      "place": "Makkah",
      "arabic": "الفِيل",
    },
    {
      "id": 106,
      "name": "Quraisy",
      "aya": 4,
      "malay": "Suku Quraisy",
      "english": "The Quraysh",
      "place": "Makkah",
      "arabic": "قُرَيْش",
    },
    {
      "id": 107,
      "name": "Al-Maa'uun",
      "aya": 7,
      "malay": "Bantuan",
      "english": "Aimsgiving",
      "place": "Makkah",
      "arabic": "المَاعُون",
    },
    {
      "id": 108,
      "name": "Al-Kauthar",
      "aya": 3,
      "malay": "Nikmat Yang Banyak",
      "english": "Abundance",
      "place": "Makkah",
      "arabic": "الكَوْثَر",
    },
    {
      "id": 109,
      "name": "Al-Kaafiruun",
      "aya": 6,
      "malay": "Orang Kafir",
      "english": "The Disbelievers",
      "place": "Makkah",
      "arabic": "الكَافِرُون",
    },
    {
      "id": 110,
      "name": "An-Nasr",
      "aya": 3,
      "malay": "Pertolongan",
      "english": "The Divine Support",
      "place": "Madinah",
      "arabic": "النَّصر",
    },
    {
      "id": 111,
      "name": "Al-Masad",
      "aya": 5,
      "malay": "Sabut",
      "english": "The Palm Fibre",
      "place": "Makkah",
      "arabic": "المَسَد",
    },
    {
      "id": 112,
      "name": "Al-Ikhlaas",
      "aya": 4,
      "malay": "Tauhid",
      "english": "Sincerity",
      "place": "Makkah",
      "arabic": "الإخْلَاص",
    },
    {
      "id": 113,
      "name": "Al-Falaq",
      "aya": 5,
      "malay": "Waktu Subuh",
      "english": "The Dawn",
      "place": "Makkah",
      "arabic": "الفَلَق",
    },
    {
      "id": 114,
      "name": "An-Naas",
      "aya": 6,
      "malay": "Manusia",
      "english": "Mankind",
      "place": "Makkah",
      "arabic": "النَّاس",
    },
    {
      "id": 115,
      "name": "Al-Mu'awwidhatain",
      "aya": 11,
      "malay": "Surah Pelindung",
      "english": "The Two Protectors",
      "place": "Makkah",
      "arabic": "المُعوِّذَتَين",
    },
    {
      "id": 116,
      "name": "Ar-Ruqyah",
      "aya": 5,
      "malay": "Ruqyah",
      "english": "Spiritual Healing",
      "place": "Makkah",
      "arabic": "الرُّقيَة",
    },
    {
      "id": 117,
      "name": "Al-Mujadalah",
      "aya": 22,
      "malay": "Perdebatan",
      "english": "The Ple",
      "place": "Madinah",
      "arabic": "المُجَادَلَة",
    },
  ];

  Map<String, dynamic>? getSurahInfo(String surahName) {
    return QuranApi.surahLocal.firstWhere(
      (item) => item['name'] == surahName,
      orElse: () => {},
    );
  }
}
